version: '3'
services:
  redis:
    image: redis
    container_name: my-redis-container
    ports:
      - "6379:6379"
        # db:
  #   image: postgres:latest
  #   container_name: my-postgres-container
  #   environment:
  #     POSTGRES_USER: myuser
  #     POSTGRES_PASSWORD: mypassword
  #     POSTGRES_DB: mydatabase
  backend:
    build: .//
    container_name: my-django-container
    ports:
      - "8000:8000"

    depends_on:
      - redis

